# Generated by Django 5.2.4 on 2025-08-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_show_name', models.CharField(help_text='Name of the TV show', max_length=50)),
                ('guess', models.CharField(help_text='Your guess of the plot', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the guess was made')),
                ('response', models.JSONField(blank=True, help_text='Response from the AI model', null=True)),
            ],
        ),
    ]
